### ISSUE TITLE
Provide motivation not to use pvp for tomland

### ISSUE THREAD

**Issue by ysangkok** [flipstone/henforcer#3]
I don't understand why tomland is pinned to 1.3.3.2 instead of allowing e.g. 1.3.3.3 which should be compatible per PVP. It would be nice if the source had documentation for this pinning, so that people could keep track of the issues that 1.3.3.3 must be having.

**Comment by telser** [comment]
Because it was a mistake. This should be fixed now.

**Comment by ysangkok** [comment]
Ok, great, thanks
